apiVersion: apps/v1beta1
kind: Deployment 
metadata: 
  name: codingchallenge 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: codingchallenge 
  template: 
    metadata:  
      labels: 
        app: codingchallenge 
    spec: 
      containers: 
        - name: codingchallenge-service 
          image: dillonlpeterson/codingchallenge:latest
          imagePullPolicy: Always
          env: 
          - name: UPDATED_AT 
            value: "Tue 20 Mar 2018 08:26:39 GMT"
          ports: 
            - containerport: 80
              name: codingchallenge